company_name = "Storack"
email = "sales@storack.com"
phone = "+86 178 6161 6766"
business_hours = "Mon–Sat, 8:00 AM–6:00 PM (GMT+8)"
address = "Hedong District, Linyi, Shandong, China"

turnstile_sitekey = "0x44AAAAAA"
